"""add provenance, parent company link and epistemic statements

Revision ID: 730e524fdce6
Revises: eacf37c1aaa8
Create Date: 2026-09-14 10:49:54.790574+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '730e524fdce6'
down_revision: str | None = 'eacf37c1aaa8'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('parent_company_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_companies_parent_company_id'), 'companies', ['parent_company_id'], unique=False)
    op.create_foreign_key(op.f('fk_companies_parent_company_id_companies'), 'companies', 'companies', ['parent_company_id'], ['id'], ondelete='SET NULL')
    op.add_column('opportunities', sa.Column('fact', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('inference', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('prediction', sa.Text(), nullable=True))
    # Added NOT NULL with a temporary server default so existing rows backfill,
    # then the default is dropped: the model is the source of truth for defaults,
    # and leaving one behind would show up as schema drift.
    op.add_column(
        'sources',
        sa.Column(
            'ingest_mode',
            sa.Enum('AUTOMATED', 'ANALYST', 'TEST', name='source_ingest_mode',
                    native_enum=False, create_constraint=True, length=48),
            nullable=False,
            server_default='AUTOMATED',
        ),
    )
    op.alter_column('sources', 'ingest_mode', server_default=None)
    op.create_index(op.f('ix_sources_ingest_mode'), 'sources', ['ingest_mode'], unique=False)

    # Alembic does not autogenerate CHECK constraints, so this one is explicit.
    op.create_check_constraint(
        'parent_is_not_self', 'companies', 'parent_company_id IS NULL OR parent_company_id <> id'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The bare name: the metadata naming convention expands it to
    # ck_companies_parent_is_not_self, and passing the expanded name would get it
    # wrapped a second time.
    op.drop_constraint('parent_is_not_self', 'companies', type_='check')
    op.drop_index(op.f('ix_sources_ingest_mode'), table_name='sources')
    op.drop_column('sources', 'ingest_mode')
    op.drop_column('opportunities', 'prediction')
    op.drop_column('opportunities', 'inference')
    op.drop_column('opportunities', 'fact')
    op.drop_constraint(op.f('fk_companies_parent_company_id_companies'), 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_parent_company_id'), table_name='companies')
    op.drop_column('companies', 'parent_company_id')
    # ### end Alembic commands ###
