"""add contact intelligence, event timing and outreach log

Contact intelligence (phone, contact kind, verification date, outreach state),
event-timing classification on opportunities, and the ``outreach_log`` table.

Hand-edited after autogeneration: the three new ``NOT NULL`` enum columns carry a
temporary ``server_default`` so existing rows backfill, then drop it again so the
model stays the single source of truth for defaults and the schema does not drift.

Revision ID: b2f09d3cd683
Revises: 730e524fdce6
Create Date: 2026-09-15 10:25:30.753308+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'b2f09d3cd683'
down_revision: str | None = '730e524fdce6'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('EMAIL_SENT', 'CALL_MADE', 'CALL_ATTEMPTED', 'LINKEDIN_MESSAGE', 'MEETING_HELD', 'PROPOSAL_SENT', 'INTRODUCTION_REQUESTED', 'NOTE', name='outreach_action', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('status_after', sa.Enum('NOT_CONTACTED', 'ATTEMPTED', 'CONTACTED', 'IN_DISCUSSION', 'MEETING_BOOKED', 'PROPOSAL_SENT', 'WON', 'LOST', 'NURTURE', name='outreach_status_after', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_follow_up_on', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('note IS NULL OR length(trim(note)) > 0', name=op.f('ck_outreach_log_note_not_blank')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_outreach_log_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_outreach_log_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_outreach_log_opportunity_id_opportunities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outreach_log'))
    )
    op.create_index('ix_outreach_log_company_time', 'outreach_log', ['company_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('ix_outreach_log_contact_id'), 'outreach_log', ['contact_id'], unique=False)
    op.create_index(op.f('ix_outreach_log_created_at'), 'outreach_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_log_opportunity_id'), 'outreach_log', ['opportunity_id'], unique=False)
    op.add_column('contacts', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('normalized_phone', sa.String(length=32), nullable=True))
    # Temporary server_default so rows that already exist get a value; dropped
    # immediately below so the model remains the only place defaults live.
    op.add_column(
        'contacts',
        sa.Column(
            'contact_kind',
            sa.Enum('NAMED_INDIVIDUAL', 'DEPARTMENT_ROUTE', 'UNKNOWN', name='contact_kind', native_enum=False, create_constraint=True, length=48),
            nullable=False,
            server_default='UNKNOWN',
        ),
    )
    op.alter_column('contacts', 'contact_kind', server_default=None)
    op.add_column('contacts', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    # Temporary server_default so rows that already exist get a value; dropped
    # immediately below so the model remains the only place defaults live.
    op.add_column(
        'contacts',
        sa.Column(
            'outreach_status',
            sa.Enum('NOT_CONTACTED', 'ATTEMPTED', 'CONTACTED', 'IN_DISCUSSION', 'MEETING_BOOKED', 'PROPOSAL_SENT', 'WON', 'LOST', 'NURTURE', name='contact_outreach_status', native_enum=False, create_constraint=True, length=48),
            nullable=False,
            server_default='NOT_CONTACTED',
        ),
    )
    op.alter_column('contacts', 'outreach_status', server_default=None)
    op.add_column('contacts', sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contacts', sa.Column('next_follow_up_on', sa.Date(), nullable=True))
    op.create_index(op.f('ix_contacts_contact_kind'), 'contacts', ['contact_kind'], unique=False)
    op.create_index(op.f('ix_contacts_next_follow_up_on'), 'contacts', ['next_follow_up_on'], unique=False)
    op.create_index(op.f('ix_contacts_normalized_phone'), 'contacts', ['normalized_phone'], unique=False)
    op.create_index(op.f('ix_contacts_outreach_status'), 'contacts', ['outreach_status'], unique=False)
    op.add_column('opportunities', sa.Column('event_date', sa.Date(), nullable=True))
    # Temporary server_default so rows that already exist get a value; dropped
    # immediately below so the model remains the only place defaults live.
    op.add_column(
        'opportunities',
        sa.Column(
            'timing_class',
            sa.Enum('IMMEDIATE', 'FUTURE_ACCOUNT', 'HISTORICAL', name='opportunity_timing_class', native_enum=False, create_constraint=True, length=48),
            nullable=False,
            server_default='FUTURE_ACCOUNT',
        ),
    )
    op.alter_column('opportunities', 'timing_class', server_default=None)
    op.add_column('opportunities', sa.Column('timing_rationale', sa.Text(), nullable=True))
    op.create_index(op.f('ix_opportunities_event_date'), 'opportunities', ['event_date'], unique=False)
    op.create_index(op.f('ix_opportunities_timing_class'), 'opportunities', ['timing_class'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_timing_class'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_event_date'), table_name='opportunities')
    op.drop_column('opportunities', 'timing_rationale')
    op.drop_column('opportunities', 'timing_class')
    op.drop_column('opportunities', 'event_date')
    op.drop_index(op.f('ix_contacts_outreach_status'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_normalized_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_next_follow_up_on'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_kind'), table_name='contacts')
    op.drop_column('contacts', 'next_follow_up_on')
    op.drop_column('contacts', 'last_contacted_at')
    op.drop_column('contacts', 'outreach_status')
    op.drop_column('contacts', 'last_verified_at')
    op.drop_column('contacts', 'contact_kind')
    op.drop_column('contacts', 'normalized_phone')
    op.drop_column('contacts', 'phone')
    op.drop_index(op.f('ix_outreach_log_opportunity_id'), table_name='outreach_log')
    op.drop_index(op.f('ix_outreach_log_created_at'), table_name='outreach_log')
    op.drop_index(op.f('ix_outreach_log_contact_id'), table_name='outreach_log')
    op.drop_index('ix_outreach_log_company_time', table_name='outreach_log')
    op.drop_table('outreach_log')
    # ### end Alembic commands ###
