"""initial schema

Revision ID: eacf37c1aaa8
Revises: 
Create Date: 2026-09-14 10:17:33.891497+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eacf37c1aaa8'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size_band', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE', 'UNKNOWN', name='company_size_band', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('event_potential_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('event_potential_score IS NULL OR (event_potential_score >= 0 AND event_potential_score <= 100)', name=op.f('ck_companies_event_potential_score_range')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_companies_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('domain', name=op.f('uq_companies_domain')),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_companies_normalized_name'))
    )
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index('ix_companies_sector_size', 'companies', ['sector', 'size_band'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('normalized_url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('COMPANY', 'GOVERNMENT', 'PROCUREMENT', 'BUSINESS_PUBLICATION', 'INDUSTRY_PUBLICATION', 'EVENT', 'PUBLIC_PROFILE', 'OTHER', name='source_type', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('adapter_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_sources_confidence_range')),
    sa.CheckConstraint('length(content_hash) = 64', name=op.f('ck_sources_content_hash_is_sha256')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_sources_content_hash')),
    sa.UniqueConstraint('normalized_url', name=op.f('uq_sources_normalized_url'))
    )
    op.create_index(op.f('ix_sources_adapter_key'), 'sources', ['adapter_key'], unique=False)
    op.create_index(op.f('ix_sources_created_at'), 'sources', ['created_at'], unique=False)
    op.create_index(op.f('ix_sources_publication_date'), 'sources', ['publication_date'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=300), nullable=True),
    sa.Column('department', sa.Enum('MARKETING', 'CORPORATE_COMMUNICATIONS', 'COMMUNICATIONS', 'PR', 'EVENTS', 'PROCUREMENT', 'BUSINESS_DEVELOPMENT', 'HR', 'OTHER', 'UNKNOWN', name='contact_department', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('normalized_email', sa.String(length=320), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('normalized_linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('email_status', sa.Enum('VERIFIED', 'PUBLIC', 'INFERRED', 'UNKNOWN', name='contact_email_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('contact_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email IS NOT NULL OR email_status = 'UNKNOWN'", name=op.f('ck_contacts_email_status_requires_email')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_contacts_confidence_range')),
    sa.CheckConstraint('contact_score >= 0 AND contact_score <= 100', name=op.f('ck_contacts_contact_score_range')),
    sa.CheckConstraint('email IS NULL OR length(trim(email)) > 0', name=op.f('ck_contacts_email_not_blank')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_contacts_name_not_blank')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_contacts_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_contacts_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('company_id', 'normalized_name', 'department', name='uq_contacts_company_person'),
    sa.UniqueConstraint('normalized_email', name=op.f('uq_contacts_normalized_email')),
    sa.UniqueConstraint('normalized_linkedin_url', name=op.f('uq_contacts_normalized_linkedin_url'))
    )
    op.create_index('ix_contacts_company_score', 'contacts', ['company_id', 'contact_score'], unique=False)
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_department'), 'contacts', ['department'], unique=False)
    op.create_index(op.f('ix_contacts_source_id'), 'contacts', ['source_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('NEW_CONTRACT', 'NEW_PROJECT', 'PROJECT_LAUNCH', 'PROJECT_COMPLETION', 'PRODUCT_LAUNCH', 'PARTNERSHIP', 'MOU', 'JOINT_VENTURE', 'INVESTMENT', 'EXPANSION', 'NEW_FACILITY', 'MARKET_ENTRY', 'NEW_TECHNOLOGY', 'DIGITAL_TRANSFORMATION', 'CUSTOMER_WIN', 'EXECUTIVE_VISIT', 'DELEGATION', 'CONFERENCE', 'EXHIBITION', 'SPONSORSHIP', 'WORKSHOP', 'SEMINAR', 'TRAINING_PROGRAM', 'ANNIVERSARY', 'MILESTONE', 'TENDER', 'PROCUREMENT', 'UNKNOWN', name='signal_type', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('evidence_level', sa.Enum('FACT', 'INFERENCE', name='signal_evidence_level', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_signals_confidence_range')),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_signals_title_not_blank')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_signals_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_signals_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_signals_dedupe_key'))
    )
    op.create_index('ix_signals_company_published', 'signals', ['company_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_signals_created_at'), 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_source_id'), 'signals', ['source_id'], unique=False)
    op.create_index(op.f('ix_signals_type'), 'signals', ['type'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('primary_contact_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('PRODUCT_LAUNCH', 'CUSTOMER_EVENT', 'CLIENT_APPRECIATION', 'PARTNER_EVENT', 'DEALER_EVENT', 'DISTRIBUTOR_EVENT', 'CONFERENCE', 'WORKSHOP', 'TECHNICAL_DAY', 'SEMINAR', 'TRAINING_EVENT', 'EXECUTIVE_MEETING', 'ROUNDTABLE', 'BUSINESS_LUNCH', 'BUSINESS_DINNER', 'VIP_DINNER', 'PRESS_EVENT', 'MEDIA_EVENT', 'EXHIBITION', 'ROADSHOW', 'TOWN_HALL', 'ANNUAL_MEETING', 'AWARDS', 'TEAM_BUILDING', 'CORPORATE_CELEBRATION', 'ANNIVERSARY', 'PROJECT_LAUNCH', 'PROJECT_KICKOFF', 'PROJECT_COMPLETION_EVENT', 'GROUNDBREAKING', 'DELEGATION_EVENT', 'HOSPITALITY', 'UNKNOWN', name='opportunity_type', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('assertion_level', sa.Enum('FACT', 'INFERENCE', 'PREDICTION', name='opportunity_assertion_level', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('event_probability', sa.Integer(), nullable=False),
    sa.Column('commercial_value', sa.Integer(), nullable=False),
    sa.Column('commercial_value_band', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='opportunity_commercial_value_band', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('contact_quality', sa.Integer(), nullable=False),
    sa.Column('timing_score', sa.Integer(), nullable=False),
    sa.Column('evidence_score', sa.Integer(), nullable=False),
    sa.Column('base_score', sa.Integer(), nullable=False),
    sa.Column('decay_factor', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Enum('EXCEPTIONAL', 'HOT', 'VERY_HIGH', 'HIGH', 'QUALIFIED', 'NOT_ELIGIBLE', name='opportunity_classification', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('why_now', sa.Text(), nullable=False),
    sa.Column('sales_angle', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Enum('CONTACT_MARKETING', 'CONTACT_COMMUNICATIONS', 'CONTACT_PROCUREMENT', 'CONTACT_PROJECT_DIRECTOR', 'REQUEST_INTRODUCTION', 'MONITOR_FOR_RFP', 'PREPARE_EVENT_CONCEPT', 'NURTURE_ACCOUNT', name='opportunity_recommended_action', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('recommended_services', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('opportunity_window', sa.Enum('DAYS_0_14', 'DAYS_15_30', 'DAYS_30_60', 'DAYS_60_90', 'MONTHS_3_6', 'MONTHS_6_12', 'UNKNOWN', name='opportunity_window', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('window_ends_on', sa.Date(), nullable=True),
    sa.Column('recommended_contact_timing', sa.Enum('IMMEDIATE', 'WITHIN_1_WEEK', 'WITHIN_2_WEEKS', 'WITHIN_1_MONTH', 'MONITOR_MONTHLY', 'MONITOR_QUARTERLY', 'RESEARCH_FIRST', name='opportunity_contact_timing', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'QUALIFIED', 'CONTACTED', 'MEETING', 'WON', 'LOST', 'NURTURE', name='opportunity_status', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('previous_score', sa.Integer(), nullable=True),
    sa.Column('previous_classification', sa.Enum('EXCEPTIONAL', 'HOT', 'VERY_HIGH', 'HIGH', 'QUALIFIED', 'NOT_ELIGIBLE', name='opportunity_previous_classification', native_enum=False, create_constraint=True, length=48), nullable=True),
    sa.Column('score_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_score BETWEEN 0 AND 100', name=op.f('ck_opportunities_base_score_range')),
    sa.CheckConstraint('commercial_value BETWEEN 0 AND 100', name=op.f('ck_opportunities_commercial_value_range')),
    sa.CheckConstraint('contact_quality BETWEEN 0 AND 100', name=op.f('ck_opportunities_contact_quality_range')),
    sa.CheckConstraint('decay_factor > 0 AND decay_factor <= 1', name=op.f('ck_opportunities_decay_factor_range')),
    sa.CheckConstraint('event_probability BETWEEN 0 AND 100', name=op.f('ck_opportunities_event_probability_range')),
    sa.CheckConstraint('evidence_score BETWEEN 0 AND 100', name=op.f('ck_opportunities_evidence_score_range')),
    sa.CheckConstraint('length(trim(sales_angle)) > 0', name=op.f('ck_opportunities_sales_angle_not_blank')),
    sa.CheckConstraint('length(trim(why_now)) > 0', name=op.f('ck_opportunities_why_now_not_blank')),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name=op.f('ck_opportunities_score_range')),
    sa.CheckConstraint('timing_score BETWEEN 0 AND 100', name=op.f('ck_opportunities_timing_score_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_opportunities_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_contact_id'], ['contacts.id'], name=op.f('fk_opportunities_primary_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_opportunities_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities')),
    sa.UniqueConstraint('signal_id', 'type', name='uq_opportunities_signal_type')
    )
    op.create_index(op.f('ix_opportunities_classification'), 'opportunities', ['classification'], unique=False)
    op.create_index(op.f('ix_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_opportunities_created_at'), 'opportunities', ['created_at'], unique=False)
    op.create_index('ix_opportunities_rank', 'opportunities', [sa.literal_column('score DESC'), 'status'], unique=False)
    op.create_index(op.f('ix_opportunities_signal_id'), 'opportunities', ['signal_id'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_type'), 'opportunities', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_signal_id'), table_name='opportunities')
    op.drop_index('ix_opportunities_rank', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_created_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_classification'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_signals_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_source_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_created_at'), table_name='signals')
    op.drop_index('ix_signals_company_published', table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_contacts_source_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_department'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_index('ix_contacts_company_score', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_publication_date'), table_name='sources')
    op.drop_index(op.f('ix_sources_created_at'), table_name='sources')
    op.drop_index(op.f('ix_sources_adapter_key'), table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_companies_sector_size', table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
